version: '2'
# Use docker-compose.prod.yml as parent configuration
services:
    homebridge:
        command: ["npm run dev"]
        environment: 
            - NODE_ENV=development
        restart: "no"
        ports:
            - "5858:5858"